chia:
  executable: C:/Users/boszek/AppData/Local/chia-blockchain
  memory: 3800
  logs: c:/Users/boszek/.chia/logs
  temps:
    - location: "G:/plot1"
      limit: 0
    - location: "H:/plot2"
      limit: 0
    - location: "D:/temp"
      limit: 0
    - location: "E:/temp"
      limit: 0
    - location: "F:/temp"
      limit: 0
  targets:
    - "J:/Chia Plots"