chia:
  python: /home/boszek/projects/chia-blockchain/venv/bin/python3.8
  executable: /home/boszek/projects/chia-blockchain/venv/bin/chia
  memory: 3800
  logs: /home/boszek/chia/logs
  temps:
    - location: "/media/boszek/Chia Toshiba 4TB/temp"
      limit: 1
  targets:
    - "/media/boszek/Chia Toshiba 4TB/Chia Plots"