chia:
  executable: C:/Users/boszek/AppData/Local/chia-blockchain
  memory: 5000
  logs: c:/Users/boszek/.chia/logs
  temps:
    - location: "G:/plot1"
      limit: 4
    - location: "H:/plot1"
      limit: 4
  targets:
    - "J:/Chia Plots"
    - "F:/Chia Plots"