chia:
  python: /home/boszek/projects/chia-blockchain/venv/bin/python3.8
  executable: /home/boszek/projects/chia-blockchain/venv/bin/chia
  memory: 3400
  logs: /home/boszek/chia/logs
  temps:
    - location: "/mnt/chiatemps980"
      limit: 3
  targets:
    - "/mnt/chiatosh4tb1"