chia:
  executable: C:/Users/boszek/AppData/Local/chia-blockchain
  memory: 4000
  threads: 3
  keyId: 3337690719
  logs: c:/Users/boszek/.chia/logs
  temps:
    - location: "E:/temp"
      limit: 3
    - location: "G:/temp"
      limit: 3
    - location: "H:/temp"
      limit: 3
    - location: "F:/temp"
      limit: 1
  targets:
    - "J:/Chia Plots"
    - "F:/Chia Plots"
    - "Z:/Chia Plots"