chia:
  executable: C:/Users/boszek/AppData/Local/chia-blockchain
  memory: 5000
  threads: 4
  logs: c:/Users/boszek/.chia/logs
  temps:
    - location: "G:/plot1"
      limit: 4
    - location: "H:/plot1"
      limit: 4
    - location: "F:/temp"
      limit: 1
  targets:
    - "J:/Chia Plots"
    - "F:/Chia Plots"
    - "Y:"
    - "X:"
    - "W:"