chia:
  executable: /home/boszek/projects/chia-blockchain/venv/bin/chia
  memory: 3500
  logs: /home/boszek/chia/logs
  temps:
    - location: "/mnt/chiatemps980"
      limit: 0
  targets:
    - "/mnt/chiatosh4tb1"