chia:
  executable: C:/Users/boszek/AppData/Local/chia-blockchain/app-1.1.2/resources/app.asar.unpacked/daemon/chia.exe
  memory: 3800
  logs: c:/Users/boszek/.chia/logs
  temps:
#    - "G:/plot1"
#    - "H:/plot2"
    - "D:/temp"
    - "E:/temp"
    - "F:/temp"
  targets:
    - "J:/Chia Plots"